name: Specs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: [ '2.7', '3.0', '3.1', '3.2', '3.3', head, jruby, jruby-head, truffleruby, truffleruby-head ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install additional dependencies
      run: |
        sudo apt update && sudo apt install postgresql-client -y
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1
      with:
        postgresql version: 13
        postgresql db: pg_fulltext_test
        postgresql user: test_user
        postgresql password: test_password

    - name: Bundle Install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Test with Rake
      run: |
        bundle exec rspec
      env:
        DATABASE_URL: postgres://test_user:test_password@localhost:5432/pg_fulltext_test
